name: Python CI/CD

on:
  push:
    branches:
      - main
      - dev
      - sphinx-docs
    tags:
      - '[0-9]+.[0-9]+.x'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python -
          export PATH="$HOME/.local/bin:$PATH"
      - name: Configure Poetry
        run: |
          poetry config virtualenvs.in-project true
      - name: Install Dependencies
        run: |
          poetry install --no-interaction
      - name: Run Pytest
        run: |
          poetry run pytest

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/sphinx-docs' || startsWith(github.ref, 'refs/tags/') && github.ref_name =~ /^([0-9]+\.)?([0-9]+)\.x/
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install Sphinx and dependencies
        run: |
          pip install sphinx
          pip install pydata-sphinx-theme
          pip install sphinx-autoapi
          pip install myst-nb
      - name: Build Documentation
        run: |
          cd docs
          make html
      - name: Upload Documentation Artifact
        uses: actions/upload-artifact@v3
        with:
          name: documentation
          path: docs/build/html
